### ISSUE TITLE
database is locked (5) (SQLITE_BUSY)

### ISSUE THREAD

**Issue by ggg4566** [Li4n0/revsuit#54]
服务器挂一天就会出现这个结果，web返回400无法查看，只能终止重新启动
<img width="997" alt="image" src="https://user-images.githubusercontent.com/7532477/170807559-8710d0ee-71f6-43ab-989e-e8f95df5a536.png">

**Comment by Li4n0** [comment]
感谢反馈，问题已在 [v0.5.1](https://github.com/Li4n0/revsuit/releases/tag/v0.5.1) 版本修复，`v0.5.0` 版本可使用 `./revsuit upgrade` 命令自动更新。如发现问题仍然存在，可在本 issue 中继续反馈。祝好。
