### ISSUE TITLE
Token错误

### ISSUE THREAD

**Issue by wiwei132** [Li4n0/revsuit#55]
使用配置文件或者随机生成的Token登录panel一直提示Token错误，无法进入后台，即使删除数据库文件重新弄也是这样

**Comment by winezer0** [comment]
0.5.0版本下，config.yaml下配置的token是可用。

通过内置功能修改了token，会导致token不可用，代码BUG。

**Comment by Li4n0** [comment]
感谢反馈，问题已在 [v0.5.1](https://github.com/Li4n0/revsuit/releases/tag/v0.5.1) 版本修复，`v0.5.0` 版本可使用 `./revsuit upgrade` 命令自动更新。如发现问题仍然存在，可在本 issue 中继续反馈。祝好。
