### ISSUE TITLE
修改token后无法登录，附简单修复

### ISSUE THREAD

**Issue by winezer0** [Li4n0/revsuit#57]
**Environments**
linux amd 64、windows amd 64

**RevSuit Version**
0.5.0

**Describe the bug**
通过内置面板修改密码后，Token头和Cookie头不统一，导致无法登录
（token更新了、但cookie未更新、且路由中先获取的是cookie中的token）

**To Reproduce**
![image](https://user-images.githubusercontent.com/46115146/186182318-2dddda24-e35d-4660-bcd6-3deb00eca28d.png)

![image](https://user-images.githubusercontent.com/46115146/186182356-a1bf54be-abe0-4166-955f-b82cffac7361.png)

![image](https://user-images.githubusercontent.com/46115146/186182367-00a48788-9332-4bce-b851-e9997bf1cf66.png)

**不优美的修复方案**
修改\pkg\server\router.go文件的30行，分别获取token值
func (revsuit *Revsuit) registerPlatformRouter() {
	// /api need Authorization
	api := revsuit.http.Router.Group(revsuit.config.AdminPathPrefix + "/api")
	api.Use(func(c *gin.Context) {
		tokenCookie, _ := c.Cookie("token")
		tokenToken := c.Request.Header.Get("Token")
		if tokenToken != revsuit.http.Token && tokenCookie != revsuit.http.Token {
			c.Abort()
			c.Status(403)
		}
	})
	revsuit.http.ApiGroup = api
       .....

**Comment by Li4n0** [comment]
感谢反馈，问题已在 [v0.5.1](https://github.com/Li4n0/revsuit/releases/tag/v0.5.1) 版本修复，`v0.5.0` 版本可使用 `./revsuit upgrade` 命令自动更新。如发现问题仍然存在，可在本 issue 中继续反馈。祝好。

**Comment by Nintyhundred** [comment]
cool
