### ISSUE TITLE
Multi threaded batch request APIs can cause database to be locked (5) (SQLITE_BUSY)

### ISSUE THREAD

**Issue by charis3306** [Li4n0/revsuit#68]
![image](https://github.com/Li4n0/revsuit/assets/84823804/11d5b9cf-9f0b-420e-891b-e8f37271d905)

**Comment by Li4n0** [comment]
Recommend to use mysql database in multi-threaded access scenario

**Comment by charis3306** [comment]
Do you mean to switch from sqlite to mysql?
