### ISSUE TITLE
Using MongoDB or Cassandra is recommended for handling high concurrency scenarios with a large number of HTTP requests and storing records

### ISSUE THREAD

**Issue by charis3306** [Li4n0/revsuit#73]
Using MongoDB or Cassandra is recommended for handling high concurrency scenarios with a large number of HTTP requests and storing records

**Comment by Li4n0** [comment]
MySQL has been more than adequate in several of my heavy usage scenarios. If you have a scenario where MySQL just doesn't cut it, feel free to discuss it in more detail.
