### ISSUE TITLE
Suggestion for log update

### ISSUE THREAD

**Issue by kknifes** [Li4n0/revsuit#74]
Hello, using your project has been quite impressive and it's truly outstanding. However, I find it bothersome to manually write a tool for deleting existing records when generating a large amount of log data. Is it possible to add a feature in the code that allows clearing the content of a specific page or all pages? I believe incorporating this functionality would greatly enhance the project.

**Comment by Li4n0** [comment]
<img width="1899" alt="image" src="https://github.com/Li4n0/revsuit/assets/34324462/6eecf17f-6ebf-49f8-8ea6-3a569613f72f">

This is an existing feature.
