### ISSUE TITLE
 WARN] context canceled

### ISSUE THREAD

**Issue by CaoaiLWT** [Li4n0/revsuit#75]
![image](https://github.com/Li4n0/revsuit/assets/85109943/48b89e42-8e3d-4ab2-8689-040379e221dd)

**Comment by Li4n0** [comment]
If you wish to resolve this issue, you need to clearly describe the scenario in which the error occurs and give the context of the error; at the very least, you should indicate whether you're using a version you compiled yourself or a released version, and what environment you're running in.
